# 1-IMPORT LIBRARIES

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 2-LOAD THE DATASET

In [3]:
covid = pd.read_csv("covid_19_india.csv")
testing = pd.read_csv("StatewiseTestingDetails.csv")
vaccine = pd.read_csv("covid_vaccine_statewise.csv")

# 3-BASIC DATASET OVERVIEW

### **3.1-DISPLAY THE FIRST 5 ROWS** ###

In [4]:
covid.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3

In [5]:
testing.head()

         Date                        State  TotalSamples Negative  Positive
0  2020-04-17  Andaman and Nicobar Islands        1403.0     1210      12.0
1  2020-04-24  Andaman and Nicobar Islands        2679.0      NaN      27.0
2  2020-04-27  Andaman and Nicobar Islands        2848.0      NaN      33.0
3  2020-05-01  Andaman and Nicobar Islands        3754.0      NaN      33.0
4  2020-05-16  Andaman and Nicobar Islands        6677.0      NaN      33.0

In [6]:
vaccine.head()

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

### **3.2-CHECK THE SHAPE** ###

In [7]:
covid.shape

(18110, 9)

In [8]:
testing.shape

(16336, 5)

In [9]:
vaccine.shape

(7845, 24)

### **3.3-CHECK COLUMN NAMES** ###

In [10]:
covid.columns

Index(['Sno', 'Date', 'Time', 'State/UnionTerritory',
       'ConfirmedIndianNational', 'ConfirmedForeignNational', 'Cured',
       'Deaths', 'Confirmed'],
      dtype='str')

In [11]:
testing.columns

Index(['Date', 'State', 'TotalSamples', 'Negative', 'Positive'], dtype='str')

In [12]:
vaccine.columns

Index(['Updated On', 'State', 'Total Doses Administered', 'Sessions',
       ' Sites ', 'First Dose Administered', 'Second Dose Administered',
       'Male (Doses Administered)', 'Female (Doses Administered)',
       'Transgender (Doses Administered)', ' Covaxin (Doses Administered)',
       'CoviShield (Doses Administered)', 'Sputnik V (Doses Administered)',
       'AEFI', '18-44 Years (Doses Administered)',
       '45-60 Years (Doses Administered)', '60+ Years (Doses Administered)',
       '18-44 Years(Individuals Vaccinated)',
       '45-60 Years(Individuals Vaccinated)',
       '60+ Years(Individuals Vaccinated)', 'Male(Individuals Vaccinated)',
       'Female(Individuals Vaccinated)', 'Transgender(Individuals Vaccinated)',
       'Total Individuals Vaccinated'],
      dtype='str')

### **3.4-CHECKS DATATYPES** ###

In [13]:
covid.dtypes

Sno                         int64
Date                          str
Time                          str
State/UnionTerritory          str
ConfirmedIndianNational       str
ConfirmedForeignNational      str
Cured                       int64
Deaths                      int64
Confirmed                   int64
dtype: object

In [14]:
testing.dtypes

Date                str
State               str
TotalSamples    float64
Negative            str
Positive        float64
dtype: object

In [15]:
vaccine.dtypes

Updated On                                 str
State                                      str
Total Doses Administered               float64
Sessions                               float64
 Sites                                 float64
First Dose Administered                float64
Second Dose Administered               float64
Male (Doses Administered)              float64
Female (Doses Administered)            float64
Transgender (Doses Administered)       float64
 Covaxin (Doses Administered)          float64
CoviShield (Doses Administered)        float64
Sputnik V (Doses Administered)         float64
AEFI                                   float64
18-44 Years (Doses Administered)       float64
45-60 Years (Doses Administered)       float64
60+ Years (Doses Administered)         float64
18-44 Years(Individuals Vaccinated)    float64
45-60 Years(Individuals Vaccinated)    float64
60+ Years(Individuals Vaccinated)      float64
Male(Individuals Vaccinated)           float64
Female(Individuals Vaccinated)         float64
Transgender(Individuals Vaccinated)    float64
Total Individuals Vaccinated           float64
dtype: object

# 4-MISSING VALUE SUMMARIES

### **4.1-CHECK MISSING VALUES** ###

In [16]:
covid.isnull().sum().sort_values(ascending=False)

Sno                         0
Date                        0
Time                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Confirmed                   0
dtype: int64

In [17]:
testing.isnull().sum().sort_values(ascending=False)

Positive        10674
Negative         9367
Date                0
TotalSamples        0
State               0
dtype: int64

In [18]:
vaccine.isnull().sum().sort_values(ascending=False)

Male(Individuals Vaccinated)           7685
Female(Individuals Vaccinated)         7685
Transgender(Individuals Vaccinated)    7685
18-44 Years (Doses Administered)       6143
45-60 Years (Doses Administered)       6143
60+ Years (Doses Administered)         6143
Sputnik V (Doses Administered)         4850
18-44 Years(Individuals Vaccinated)    4112
60+ Years(Individuals Vaccinated)      4111
45-60 Years(Individuals Vaccinated)    4111
AEFI                                   2407
Total Individuals Vaccinated           1926
Female (Doses Administered)             384
Transgender (Doses Administered)        384
Male (Doses Administered)               384
Sessions                                224
Total Doses Administered                224
 Sites                                  224
Second Dose Administered                224
First Dose Administered                 224
 Covaxin (Doses Administered)           224
CoviShield (Doses Administered)         224
State                                     0
Updated On                                0
dtype: int64

### **4.2-CHECK DUPLICATE VALUES** ###

In [19]:
covid.duplicated().sum()

np.int64(0)

In [20]:
testing.duplicated().sum()

np.int64(1)

In [21]:
vaccine.duplicated().sum()

np.int64(0)

# 5-DATA VALIDATION CHECKLIST

### **5.1-CHECKS FOR NEGATIVE VALUES** ###

In [22]:
print((covid["Confirmed"] < 0).sum())
print((covid["Cured"] < 0).sum())
print((covid["Deaths"] < 0).sum())

0
0
0

In [23]:
testing.select_dtypes(include="number").lt(0).sum()

TotalSamples    0
Positive        0
dtype: int64

In [24]:
vaccine.select_dtypes(include="number").lt(0).sum()

Total Doses Administered               0
Sessions                               0
 Sites                                 0
First Dose Administered                0
Second Dose Administered               0
Male (Doses Administered)              0
Female (Doses Administered)            0
Transgender (Doses Administered)       0
 Covaxin (Doses Administered)          0
CoviShield (Doses Administered)        0
Sputnik V (Doses Administered)         0
AEFI                                   0
18-44 Years (Doses Administered)       0
45-60 Years (Doses Administered)       0
60+ Years (Doses Administered)         0
18-44 Years(Individuals Vaccinated)    0
45-60 Years(Individuals Vaccinated)    0
60+ Years(Individuals Vaccinated)      0
Male(Individuals Vaccinated)           0
Female(Individuals Vaccinated)         0
Transgender(Individuals Vaccinated)    0
Total Individuals Vaccinated           0
dtype: int64

### **5.2-CHECK LOGICAL ERRORS** ###

In [25]:
covid[
    (covid["Cured"] > covid["Confirmed"]) |
    (covid["Deaths"] > covid["Confirmed"])
]

Empty DataFrame
Columns: [Sno, Date, Time, State/UnionTerritory, ConfirmedIndianNational, ConfirmedForeignNational, Cured, Deaths, Confirmed]
Index: []

In [26]:
vaccine[vaccine["Second Dose Administered"] > vaccine["First Dose Administered"]]

Empty DataFrame
Columns: [Updated On, State, Total Doses Administered, Sessions,  Sites , First Dose Administered, Second Dose Administered, Male (Doses Administered), Female (Doses Administered), Transgender (Doses Administered),  Covaxin (Doses Administered), CoviShield (Doses Administered), Sputnik V (Doses Administered), AEFI, 18-44 Years (Doses Administered), 45-60 Years (Doses Administered), 60+ Years (Doses Administered), 18-44 Years(Individuals Vaccinated), 45-60 Years(Individuals Vaccinated), 60+ Years(Individuals Vaccinated), Male(Individuals Vaccinated), Female(Individuals Vaccinated), Transgender(Individuals Vaccinated), Total Individuals Vaccinated]
Index: []

[0 rows x 24 columns]

### **5.3-VALIDATE DATE** ###

In [27]:
covid["Date"] = pd.to_datetime(covid["Date"])

testing["Date"] = pd.to_datetime(testing["Date"])

vaccine["Updated On"] = pd.to_datetime(vaccine["Updated On"])

C:\Users\soura\AppData\Local\Temp\ipykernel_27476\1060761499.py:5: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  vaccine["Updated On"] = pd.to_datetime(vaccine["Updated On"])

### **5.4-CHECK STATE NAME** ###

In [28]:
print(covid["State/UnionTerritory"].unique())

print(testing["State"].unique())

print(vaccine["State"].unique())

<ArrowStringArray>
[                                  'Kerala',
                                'Telengana',
                                    'Delhi',
                                'Rajasthan',
                            'Uttar Pradesh',
                                  'Haryana',
                                   'Ladakh',
                               'Tamil Nadu',
                                'Karnataka',
                              'Maharashtra',
                                   'Punjab',
                        'Jammu and Kashmir',
                           'Andhra Pradesh',
                              'Uttarakhand',
                                   'Odisha',
                               'Puducherry',
                              'West Bengal',
                             'Chhattisgarh',
                               'Chandigarh',
                                  'Gujarat',
                         'Himachal Pradesh',
                           'Madhya Pradesh',
                                    'Bihar',
                                  'Manipur',
                                  'Mizoram',
              'Andaman and Nicobar Islands',
                                      'Goa',
                               'Unassigned',
                                    'Assam',
                                'Jharkhand',
                        'Arunachal Pradesh',
                                  'Tripura',
                                 'Nagaland',
                                'Meghalaya',
 'Dadra and Nagar Haveli and Daman and Diu',
         'Cases being reassigned to states',
                                   'Sikkim',
                              'Daman & Diu',
                              'Lakshadweep',
                                'Telangana',
                   'Dadra and Nagar Haveli',
                                'Bihar****',
                        'Madhya Pradesh***',
                        'Himanchal Pradesh',
                               'Karanataka',
                           'Maharashtra***']
Length: 46, dtype: str
<ArrowStringArray>
[             'Andaman and Nicobar Islands',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                        'Jammu and Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str
<ArrowStringArray>
[                                   'India',
              'Andaman and Nicobar Islands',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                        'Jammu and Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 37, dtype: str

### **5.5-CHECK THE RANGE OF NUMERICAL VALUES** ###

In [29]:
covid.describe()

testing.describe()

vaccine.describe()

,Updated On,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),Covaxin (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
count,7845,7.621000e+03,7.621000e+03,7621.000000,7.621000e+03,7.621000e+03,7.461000e+03,7.461000e+03,7461.000000,7.621000e+03,...,1.702000e+03,1.702000e+03,1.702000e+03,3.733000e+03,3.734000e+03,3.734000e+03,1.600000e+02,1.600000e+02,160.000000,5.919000e+03
mean,2021-05-01 12:19:32.925430,9.188171e+06,4.792358e+05,2282.872064,7.414415e+06,1.773755e+06,3.620156e+06,3.168416e+06,1162.978019,1.044669e+06,...,8.773958e+06,7.442161e+06,5.641605e+06,1.395895e+06,2.916515e+06,2.627444e+06,4.461687e+07,3.951018e+07,12370.543750,4.547842e+06
min,2021-01-16 00:00:00,7.000000e+00,0.000000e+00,0.000000,7.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,0.000000,0.000000e+00,...,2.662400e+04,1.681500e+04,9.994000e+03,1.059000e+03,1.136000e+03,5.580000e+02,2.375700e+04,2.451700e+04,2.000000,7.000000e+00
25%,2021-03-10 00:00:00,1.356570e+05,6.004000e+03,69.000000,1.166320e+05,1.283100e+04,5.655500e+04,5.210700e+04,8.000000,0.000000e+00,...,4.344842e+05,2.326275e+05,1.285605e+05,5.655400e+04,9.248225e+04,5.615975e+04,5.739350e+06,5.023407e+06,1278.750000,7.427550e+04
50%,2021-05-02 00:00:00,8.182020e+05,4.547000e+04,597.000000,6.614590e+05,1.388180e+05,3.897850e+05,3.342380e+05,113.000000,1.185100e+04,...,3.095970e+06,2.695938e+06,1.805696e+06,2.947270e+05,8.330395e+05,7.887425e+05,3.716590e+07,3.365402e+07,8007.500000,4.022880e+05
75%,2021-06-24 00:00:00,6.625243e+06,3.428690e+05,1708.000000,5.387805e+06,1.166434e+06,2.735777e+06,2.561513e+06,800.000000,7.579300e+05,...,7.366241e+06,6.969726e+06,5.294763e+06,9.105160e+05,2.499280e+06,2.337874e+06,7.441663e+07,6.685368e+07,19851.000000,3.501562e+06
max,2021-08-16 00:00:00,5.132284e+08,3.501031e+07,73933.000000,4.001504e+08,1.130780e+08,2.701636e+08,2.395186e+08,98275.000000,6.236742e+07,...,2.243304e+08,1.667575e+08,1.186927e+08,9.224315e+07,9.096888e+07,6.731098e+07,1.349420e+08,1.156684e+08,46462.000000,2.506569e+08
std,NaN,3.746180e+07,1.911511e+06,7275.973730,2.995209e+07,7.570382e+06,1.737938e+07,1.515310e+07,5931.353995,4.452259e+06,...,2.660829e+07,2.225999e+07,1.681650e+07,5.501454e+06,9.567607e+06,8.192225e+06,3.950749e+07,3.417684e+07,12485.026753,1.834182e+07

# 6-CLEANING DATASET

In [30]:
covid_clean = covid.drop_duplicates().dropna()

In [31]:
testing_clean = testing.drop_duplicates().dropna()

In [32]:
vaccine_clean = vaccine.drop_duplicates().dropna()

In [33]:
covid_clean.to_csv("covid_clean.csv", index=False)

testing_clean.to_csv("testing_clean.csv", index=False)

vaccine_clean.to_csv("vaccine_clean.csv", index=False)